$(env node_ns):
  $(env node_name):
    ros__parameters:
      height: $(env height)
      width: $(env width)
      create_player_topic: "$(env create_player_topic)"
      get_status_topic: "$(env get_status_topic)"
      team: $(env team_A)